### ISSUE TITLE
Error: listen EADDRINUSE: address already in use /socket_dir/file.sock

### ISSUE THREAD

**Issue by johnweland** [johnweland/docker-sidecar#3]
**Describe the bug**
Currently, these containers communicate over a UNIX domain socket in a directory called `var/run` created at runtime. If this folder is present when you issue the `docker-compose up` command you will get the following error.
```bash
Error: listen EADDRINUSE: address already in use /socket_dir/file.sock
```

**To Reproduce**
1. Create folders `var/run` in the project directory 
2. Run `docker-compose up`
3. See error

```bash
Error: listen EADDRINUSE: address already in use /socket_dir/file.sock
```

**Expected behavior**
If the folder doesn't exist, create it; if it does mount to it.

An improved method would actually be to not require a host mount at all _example below_. However, this too is not working as expected (same error)

<table>
<tr>
<th>Current</th>
<th>Goal</th>
</tr>
<tr>
<td>

```yml
version: '3.8'
services:
  sidecar:
    ...
    volumes:
      - ./src:/home/node/.../src
      - ./nodemon.json:/home/node/...
      - ./var/run:/socket_dir/:rw
    ...
  client:
    ...
    volumes: 
      - ./var/run:/socket_dir/:rw 
    ...
```
</td>
<td>

```yml
version: '3.8'
services:
  sidecar:
    ...
    volumes:
      - ./src:/home/node/.../src
      - ./nodemon.json:/home/node/...
      - socket-volume:/socket_dir/:rw
    ...
  client:
    ...
    volumes: 
      - socket-volume:/socket_dir/:rw 
    ...
volumes:
    - socket-volume:
```
</td>
</tr>
</table>
